language: node_js

node_js:
  - 5

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

env:
  global:
    - NODE_ENV=test
    - CXX=g++-4.9

cache:
  apt: true
  directories:
    - node_modules
